// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SimpleSongs.Data.Context;

#nullable disable

namespace SimpleSongs.Data.Migrations
{
    [DbContext(typeof(SongsContext))]
    [Migration("20220606120820_First-Migration")]
    partial class FirstMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("SimpleSongs.Data.Entities.Song", b =>
                {
                    b.Property<Guid>("SongId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AlbumName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Length")
                        .HasColumnType("float");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SongId");

                    b.ToTable("Songs");

                    b.HasData(
                        new
                        {
                            SongId = new Guid("a5228fde-ac2e-4c14-8219-ddc33485b472"),
                            AlbumName = "Imagine",
                            Author = "John Lennon",
                            Length = 3.0499999999999998,
                            Title = "Imagine"
                        },
                        new
                        {
                            SongId = new Guid("fcad7381-12d8-4993-a466-17312bbe77d2"),
                            AlbumName = "Help!",
                            Author = "The Beatles",
                            Length = 2.0499999999999998,
                            Title = "Yesterday"
                        },
                        new
                        {
                            SongId = new Guid("0ab73d2b-ab53-438f-8217-79a9bac414dd"),
                            AlbumName = "Nevermind",
                            Author = "Nirvana",
                            Length = 5.0199999999999996,
                            Title = "Smells Like Teen Spirit"
                        },
                        new
                        {
                            SongId = new Guid("d94cf4a0-6287-485d-896b-8e351b66e3c7"),
                            AlbumName = "A Night at the Opera",
                            Author = "Queen",
                            Length = 5.9199999999999999,
                            Title = "Bohemian Rhapsody"
                        },
                        new
                        {
                            SongId = new Guid("8e529ff2-111b-4655-b956-e8cde2bd3946"),
                            AlbumName = "HIStory: Past, Present and Future, Book I",
                            Author = "Michael Jackson",
                            Length = 6.9199999999999999,
                            Title = "Earth Song"
                        },
                        new
                        {
                            SongId = new Guid("4a4a0c57-1ac5-4a6b-b4da-ed03732441e7"),
                            AlbumName = "Ray of Light",
                            Author = "Madonna",
                            Length = 6.2000000000000002,
                            Title = "Frozen"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
